### ISSUE TITLE
Pixtral fails with this JPEG and I'm not sure why

### ISSUE THREAD

**Issue by simonw** [mistralai/platform-docs-public#149]
https://static.simonwillison.net/static/2024/rocks.jpeg is a JPEG image, but Pixtral says this when I pass the URL (using the La Plateforme API):

> `Error: 500: invalid_request_error - Image https://static.simonwillison.n has an invalid format.Allowed formats are JPEG,PNG,WEBP,GIF.`

Other JPEGs I have work fine, like this one: https://static.simonwillison.net/static/2024/earth.jpg

**Comment by jean-malo** [comment]
Hi @simonw 
Thanks for the report, looking into it.

**Comment by jean-malo** [comment]
Fixed, thanks a lot @simonw !
