### ISSUE TITLE
https://mistral.ai/ link to LinkedIn

### ISSUE THREAD

**Issue by Eureka187** [mistralai/platform-docs-public#27]
https://mistral.ai/ link to LinkedIn does not direct you to Mistral LinkedIn page.
When clicked it takes you again to https://mistral.ai/ again instead of taking you to https://www.linkedin.com/company/mistralai/

**Comment by kghamilton89** [comment]
Please note, @Eureka187 is referencing LinkedIn icon on Mistral AI top-level domain:

![image](https://github.com/mistralai/platform-docs-public/assets/29099829/272ad93d-d374-49aa-914f-2af0cb4bff00)

**Comment by sophiamyang** [comment]
Fixed thanks!
